"use client";
/* eslint-disable @next/next/no-img-element, @next/next/no-html-link-for-pages, @typescript-eslint/no-explicit-any, react-hooks/exhaustive-deps */

import { FormEvent, useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { getSupabaseBrowserClient } from "../lib/supabase/client";
import "./platform.css";
import "./platform-overrides.css";

type PublicTournament={id:string;name:string;slug:string;image_url:string|null;description:string|null;status:string;organizations:{slug:string;name:string}|null};
type MyLeague={id:string;name:string;slug:string;description:string|null;subdomain_requests:{status:string;admin_notes:string|null}|null};
const slugify=(value:string)=>value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"").slice(0,32);
const reserved=new Set(["www","app","admin","api","mail","soporte","ayuda","liguita"]);

export function PlatformLanding(){
 const supabase=useMemo(()=>getSupabaseBrowserClient(),[]);
 const [user,setUser]=useState<User|null>(null),[tournaments,setTournaments]=useState<PublicTournament[]>([]),[leagues,setLeagues]=useState<MyLeague[]>([]);
 const [showAuth,setShowAuth]=useState(false),[showLeague,setShowLeague]=useState(false),[authMode,setAuthMode]=useState<"login"|"register">("login");
 const [authMessage,setAuthMessage]=useState(""),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[created,setCreated]=useState<MyLeague|null>(null);
 const [leagueName,setLeagueName]=useState(""),[subdomain,setSubdomain]=useState(""),[slugTouched,setSlugTouched]=useState(false);
 const loadLeagues=async(current:User|null)=>{if(!supabase||!current)return setLeagues([]);const {data}=await supabase.from("organizations").select("id,name,slug,description,subdomain_requests(status,admin_notes)").eq("owner_id",current.id).order("created_at",{ascending:false});setLeagues((data??[]).map((x:any)=>({...x,subdomain_requests:Array.isArray(x.subdomain_requests)?x.subdomain_requests[0]??null:x.subdomain_requests})) as MyLeague[]);};
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>{const current=data.session?.user??null;setUser(current);loadLeagues(current);});const {data:listener}=supabase.auth.onAuthStateChange((_e,session)=>{const current=session?.user??null;setUser(current);loadLeagues(current);});supabase.from("tournaments").select("id,name,slug,image_url,description,status,organizations(slug,name)").eq("is_public",true).order("created_at",{ascending:false}).then(({data})=>setTournaments((data??[]) as unknown as PublicTournament[]));return()=>listener.subscription.unsubscribe();},[supabase]);
 const login=async()=>{if(supabase)await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${window.location.origin}/`}});};
 const emailAuth=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!supabase)return;setSaving(true);setAuthMessage("");const f=new FormData(e.currentTarget),email=String(f.get("email")||"").trim(),password=String(f.get("password")||"");if(authMode==="register"){const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:`${window.location.origin}/`}});if(error)setAuthMessage(error.message);else if(data.session)setShowAuth(false);else setAuthMessage("Revisa tu correo y confirma el enlace para activar tu cuenta.");}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setAuthMessage("No pudimos ingresar. Revisa el correo y la contraseña.");else setShowAuth(false);}setSaving(false);};
 const openLeague=()=>user?setShowLeague(true):setShowAuth(true);
 const submitLeague=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!supabase||!user)return;setSaving(true);setMessage("");const f=new FormData(e.currentTarget),clean=slugify(subdomain);if(clean.length<3||reserved.has(clean)){setMessage(clean.length<3?"El subdominio debe tener al menos 3 caracteres.":"Ese subdominio está reservado. Elige otro.");setSaving(false);return;}const {data:occupied}=await supabase.from("organizations").select("id").eq("slug",clean).maybeSingle();if(occupied){setMessage("Ese subdominio ya está ocupado. Prueba otra opción.");setSaving(false);return;}const org=await supabase.from("organizations").insert({owner_id:user.id,name:leagueName.trim(),slug:clean,description:String(f.get("description")||""),contact_name:String(f.get("contactName")||""),contact_phone:String(f.get("phone")||""),contact_email:user.email||""}).select("id,name,slug,description").single();if(org.error){setMessage(org.error.message);setSaving(false);return;}const req=await supabase.from("subdomain_requests").insert({organization_id:org.data.id,requested_by:user.id,requested_subdomain:clean,status:"pending"}).select("status,admin_notes").single();if(req.error){setMessage("La liga se creó, pero la solicitud requiere revisión manual.");setSaving(false);return;}const item={...org.data,subdomain_requests:req.data} as MyLeague;setCreated(item);setLeagues(c=>[item,...c]);setSaving(false);};
 const tournamentUrl=(t:PublicTournament)=>t.organizations?.slug?`/organizaciones/${t.organizations.slug}/torneos/${t.slug}`:`/torneos/${t.slug}`;
 return <main className="platform">
  <header className="platformHeader"><a className="platformBrand" href="/"><img src="/liguita-logo-google-white.png" alt="Liguita"/><b>LIGUITA</b></a><nav><a href="#organizadores">Organizadores</a><a href="#torneos">Torneos</a></nav>{user?<div className="ownerActions"><button className="outlineBtn" onClick={openLeague}>+ Registrar mi liga</button><button className="outlineBtn" onClick={()=>supabase?.auth.signOut()}>Salir</button></div>:<button className="outlineBtn" onClick={()=>setShowAuth(true)}>Ingresar / Registrarme</button>}</header>
  <section className="platformHero"><div><span className="pill">TU CAMPEONATO, TU COMUNIDAD</span><h1>Organiza tu fútbol.<br/><em>Hazlo inolvidable.</em></h1><p>Crea tus ligas y torneos, administra equipos, partidos y estadísticas, y comparte toda la emoción desde un solo lugar.</p><div className="heroButtons"><button className="primaryBtn" onClick={openLeague}>Registrar mi liga →</button><a href="#torneos">Ver campeonatos</a></div><small>✓ Enlace público propio · ✓ Varios torneos · ✓ Resultados y estadísticas</small></div><div className="heroLogo"><img src="/liguita-logo-white.png" alt="Logo Liguita"/></div></section>
  <section id="organizadores" className="how"><p className="sectionLabel">EMPIEZA EN MINUTOS</p><h2>Tu liga tiene su propio espacio</h2><div className="howGrid">{[["01","Crea tu cuenta","Regístrate con Google o correo y registra los datos de tu liga."],["02","Elige tu subdominio","Solicita un nombre único como laplayita.liguita.co. Lo activamos después de verificarlo."],["03","Publica tus torneos","Crea varios campeonatos y comparte resultados, tablas, goleadores y calendario."]].map(([n,t,d])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  {user&&<section className="ownerDashboard"><div><p className="sectionLabel">MI CUENTA</p><h2>Mis ligas</h2></div><button className="primaryBtn" onClick={openLeague}>+ Registrar otra liga</button><div className="leagueList">{leagues.length?leagues.map(l=><article key={l.id}><div><span className={`requestStatus ${l.subdomain_requests?.status||"pending"}`}>{l.subdomain_requests?.status==="active"?"Subdominio activo":l.subdomain_requests?.status==="rejected"?"Requiere cambios":"Pendiente de activación"}</span><h3>{l.name}</h3><a href={`/organizaciones/${l.slug}`}>liguita.co/organizaciones/{l.slug}</a><small>{l.subdomain_requests?.status==="active"?`También disponible en ${l.slug}.liguita.co`:"Este enlace provisional ya funciona mientras activamos el subdominio."}</small></div><a className="outlineBtn" href={`/organizaciones/${l.slug}`}>Ver espacio →</a></article>):<div className="noTournaments"><h3>Aún no has registrado una liga</h3><p>Solicita tu espacio y comienza a publicar campeonatos.</p></div>}</div></section>}
  <section className="notifications"><div><p className="sectionLabel">LA HINCHADA SIEMPRE INFORMADA</p><h2>Cada gol se siente al instante.</h2><p>Los seguidores podrán conocer goles, tarjetas, resultados, próximos partidos y novedades de sus campeonatos favoritos.</p></div><div className="phoneMock"><span>⚽ GOL · AHORA</span><b>Deportivo Bahía 2–1 Real Ciénaga</b><small>Samuel Rojas · 67&apos;</small></div></section>
  <section id="torneos" className="tournamentCatalog"><p className="sectionLabel">COMPETENCIAS</p><h2>Campeonatos disponibles</h2>{tournaments.length?<div className="catalogGrid">{tournaments.map(t=><a key={t.id} href={tournamentUrl(t)}><div style={{backgroundImage:`url(${t.image_url||"/liguita-logo-white.png"})`}}/><span>{t.organizations?.name||t.status}</span><h3>{t.name}</h3><p>{t.description||"Consulta partidos, equipos y estadísticas."}</p><small>Ver campeonato →</small></a>)}</div>:<div className="noTournaments"><img src="/liguita-logo-google-white.png" alt=""/><h3>Próximamente nuevos campeonatos</h3><p>Los torneos públicos aparecerán aquí.</p></div>}</section>
  <section className="finalCta"><h2>¿Listo para organizar tu campeonato?</h2><button className="primaryBtn" onClick={openLeague}>Registrar mi liga →</button></section><footer className="platformFooter"><b>LIGUITA</b><span>© 2026 · Hecho en Colombia 🇨🇴</span><div><a href="/privacidad">Privacidad</a><a href="/terminos">Términos</a></div></footer>
  {showAuth&&<div className="createOverlay"><form className="authCard" onSubmit={emailAuth}><button type="button" className="modalClose" onClick={()=>setShowAuth(false)}>×</button><img src="/liguita-logo-google-white.png" alt="Liguita"/><p className="sectionLabel">BIENVENIDO A LIGUITA</p><h2>{authMode==="register"?"Crea tu cuenta":"Inicia sesión"}</h2><p>Ingresa para registrar y administrar tus ligas y torneos.</p><button type="button" className="googleAuthBtn" onClick={login}><b>G</b> Continuar con Google</button><div className="authDivider"><span>o usa tu correo</span></div><label>Correo electrónico<input name="email" type="email" required/></label><label>Contraseña<input name="password" type="password" required minLength={6}/></label>{authMessage&&<div className="authMessage">{authMessage}</div>}<button className="primaryBtn wide" disabled={saving}>{saving?"Procesando…":authMode==="register"?"Registrarme":"Ingresar"}</button><button type="button" className="authSwitch" onClick={()=>setAuthMode(authMode==="register"?"login":"register")}>{authMode==="register"?"Ya tengo cuenta · Iniciar sesión":"No tengo cuenta · Registrarme"}</button><small>Al continuar aceptas nuestros <a href="/terminos">Términos</a> y la <a href="/privacidad">Política de privacidad</a>.</small></form></div>}
  {showLeague&&<div className="createOverlay"><form className="createTournament" onSubmit={submitLeague}><button type="button" className="modalClose" onClick={()=>{setShowLeague(false);setCreated(null);}}>×</button>{created?<div className="createdSuccess"><span>✓</span><h2>¡Tu liga fue registrada!</h2><p>Ya puedes comenzar con este enlace provisional:</p><a href={`/organizaciones/${created.slug}`}>https://liguita.co/organizaciones/{created.slug}</a><div className="pendingNotice"><b>Subdominio solicitado</b><br/>{created.slug}.liguita.co<br/><small>Lo revisaremos y activaremos manualmente.</small></div><a className="primaryBtn" href={`/organizaciones/${created.slug}`}>Ir a mi liga</a></div>:<><p className="sectionLabel">NUEVO CLIENTE</p><h2>Registra tu liga</h2><p>Primero creamos el espacio de tu organización. Allí podrás publicar todos sus torneos.</p><label>Nombre de la liga u organización<input required value={leagueName} onChange={e=>{const value=e.target.value;setLeagueName(value);if(!slugTouched)setSubdomain(slugify(value).replace(/^(liga|torneo)-?/,""));}} placeholder="Liga La Playita"/></label><label>Subdominio solicitado<div className="domainInput"><input required minLength={3} value={subdomain} onChange={e=>{setSlugTouched(true);setSubdomain(slugify(e.target.value));}} placeholder="laplayita"/><b>.liguita.co</b></div><small>Solo letras, números y guiones. Debe ser único.</small></label><label>Descripción breve<textarea name="description" rows={3}/></label><div className="formPair"><label>Persona de contacto<input name="contactName" required defaultValue={user?.user_metadata?.full_name||""}/></label><label>Celular / WhatsApp<input name="phone" type="tel" required/></label></div>{message&&<div className="formMessage">{message}</div>}<button className="primaryBtn wide" disabled={saving}>{saving?"Registrando…":"Registrar liga y solicitar subdominio"}</button></>}</form></div>}
 </main>;
}
