"use client";
/* eslint-disable @next/next/no-html-link-for-pages, @typescript-eslint/no-explicit-any, react-hooks/exhaustive-deps */
import { FormEvent,useEffect,useMemo,useState } from "react";
import { getSupabaseBrowserClient } from "../lib/supabase/client";
import "./platform.css";import "./platform-overrides.css";
const slugify=(v:string)=>v.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"").slice(0,48);
export function TournamentAdmin({id}:{id:string}){
 const supabase=useMemo(()=>getSupabaseBrowserClient(),[]),[tab,setTab]=useState("equipos"),[user,setUser]=useState<any>(null),[t,setT]=useState<any>(null),[teams,setTeams]=useState<any[]>([]),[apps,setApps]=useState<any[]>([]),[venues,setVenues]=useState<any[]>([]),[matches,setMatches]=useState<any[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 const load=async()=>{if(!supabase)return;setLoading(true);const {data:{user:u}}=await supabase.auth.getUser();setUser(u);if(!u){setLoading(false);return;}const q=await supabase.from("tournaments").select("*,organizations(name,slug)").eq("id",id).eq("owner_id",u.id).maybeSingle();setT(q.data);if(q.data){const [a,b,c,d]=await Promise.all([supabase.from("teams").select("*").eq("tournament_id",id).order("created_at"),supabase.from("team_applications").select("*").eq("tournament_id",id).order("created_at"),supabase.from("venues").select("*").eq("tournament_id",id).order("name"),supabase.from("matches").select("*,home:teams!matches_home_team_id_fkey(name),away:teams!matches_away_team_id_fkey(name),venue:venues(name)").eq("tournament_id",id).order("scheduled_at")]);setTeams(a.data??[]);setApps(b.data??[]);setVenues(c.data??[]);setMatches(d.data??[]);}setLoading(false);};
 useEffect(()=>{void load();},[supabase,id]);
 const copy=()=>navigator.clipboard.writeText(`${location.origin}/organizaciones/${t.organizations.slug}/torneos/${t.slug}?inscribir=1`).then(()=>setMessage("Enlace de inscripción copiado."));
 const addTeam=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const name=String(f.get("name")||"");const {error}=await supabase!.from("teams").insert({tournament_id:id,owner_id:user.id,name,slug:`${slugify(name)}-${Date.now().toString().slice(-5)}`,coach_name:String(f.get("coach")||""),shirt_color:String(f.get("shirt")||""),shorts_color:String(f.get("shorts")||""),socks_color:String(f.get("socks")||""),approved:true,approved_by:user.id,approved_at:new Date().toISOString()});if(error)setMessage(error.message);else{e.currentTarget.reset();setMessage("Equipo registrado y aprobado.");await load();}};
 const createTeamFromApplication=async(a:any)=>{const {data:existing}=await supabase!.from("teams").select("id").eq("application_id",a.id).maybeSingle();if(existing)return null;const {error}=await supabase!.from("teams").insert({tournament_id:id,application_id:a.id,owner_id:a.applicant_id,name:a.team_name,slug:`${slugify(a.team_name)}-${Date.now().toString().slice(-5)}`,coach_name:a.requested_role==="coach"?a.representative_name:"",shirt_color:"Por definir",shorts_color:"Por definir",socks_color:"Por definir",approved:true,approved_by:user.id,approved_at:new Date().toISOString()});return error;};
 const completeApprovedTeam=async(a:any)=>{const error=await createTeamFromApplication(a);setMessage(error?error.message:"Ficha del equipo creada. Ya puedes verla y editarla.");await load();};
 const review=async(a:any,status:"approved"|"rejected")=>{const {error}=await supabase!.from("team_applications").update({status,reviewed_by:user.id,reviewed_at:new Date().toISOString()}).eq("id",a.id);if(error){setMessage(error.message);await load();return;}if(status==="approved"){const teamError=await createTeamFromApplication(a);setMessage(teamError?`La solicitud fue aprobada, pero no se pudo crear el equipo: ${teamError.message}`:"Solicitud aprobada y ficha del equipo creada.");}else setMessage("Solicitud rechazada.");await load();};
 const addVenue=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form),name=String(f.get("name")||"").trim(),address=String(f.get("address")||"").trim();if(venues.some(v=>v.name.trim().toLocaleLowerCase("es")===name.toLocaleLowerCase("es"))){setMessage(`La cancha “${name}” ya está registrada en este torneo.`);return;}const {error}=await supabase!.from("venues").insert({tournament_id:id,name,address});if(error)setMessage(error.code==="23505"?`La cancha “${name}” ya está registrada en este torneo.`:"No pudimos guardar la cancha. Intenta nuevamente.");else{form.reset();setMessage("Cancha agregada correctamente.");await load();}};
 const addMatch=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),home=String(f.get("home")),away=String(f.get("away"));if(home===away)return setMessage("Elige dos equipos diferentes.");const {error}=await supabase!.from("matches").insert({tournament_id:id,home_team_id:home,away_team_id:away,venue_id:String(f.get("venue"))||null,scheduled_at:String(f.get("date"))?new Date(String(f.get("date"))).toISOString():null,status:"scheduled"});if(error)setMessage(error.message);else{e.currentTarget.reset();await load();}};
 const autoSchedule=async()=>{if(teams.filter(x=>x.approved).length<2)return setMessage("Aprueba al menos dos equipos.");if(matches.length&&!confirm("Ya existen partidos. ¿Deseas agregar otra programación?"))return;const list=teams.filter(x=>x.approved).map(x=>x.id);if(list.length%2)list.push("");const rows:any[]=[];let arr=[...list];let day=new Date(t.start_date+"T15:00:00");for(let leg=0;leg<(t.round_robin_legs||1);leg++){for(let r=0;r<arr.length-1;r++){for(let i=0;i<arr.length/2;i++){const x=arr[i],y=arr[arr.length-1-i];if(x&&y){const swap=(r+i+leg)%2===1;rows.push({tournament_id:id,home_team_id:swap?y:x,away_team_id:swap?x:y,round_number:r+1+leg*(arr.length-1),scheduled_at:new Date(day).toISOString(),venue_id:venues.length?venues[rows.length%venues.length].id:null,status:"scheduled"});day.setDate(day.getDate()+7);}}arr=[arr[0],arr[arr.length-1],...arr.slice(1,-1)];}}const {error}=await supabase!.from("matches").insert(rows);setMessage(error?error.message:`Se crearon ${rows.length} partidos automáticamente.`);await load();};
 const saveSettings=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),status=String(f.get("status"));if(status!==t.status&&!confirm(`¿Estás seguro de cambiar el estado del torneo a ${status==="in_progress"?"En curso":status==="finished"?"Finalizado":"Inscripciones"}?`))return;const {error}=await supabase!.from("tournaments").update({name:String(f.get("name")),start_date:String(f.get("startDate")),format:String(f.get("format")),next_stage_format:String(f.get("nextStage")),players_on_field:Number(f.get("players")),qualifiers:Number(f.get("qualifiers")),round_robin_legs:Number(f.get("legs")),registration_fee:Number(f.get("fee")),status:status as any}).eq("id",id);setMessage(error?error.message:"Torneo actualizado.");await load();};
 const updateMatch=async(m:any)=>{const date=prompt("Nueva fecha y hora (AAAA-MM-DDTHH:MM)",m.scheduled_at?.slice(0,16)||"");if(date===null)return;const venue=prompt("ID de cancha (puedes copiarlo desde la lista)",m.venue_id||"");const {error}=await supabase!.from("matches").update({scheduled_at:date?new Date(date).toISOString():null,venue_id:venue||null}).eq("id",m.id);setMessage(error?error.message:"Partido actualizado.");await load();};
 if(loading)return <main className="realPanelState"><h1>Cargando torneo…</h1></main>;if(!user)return <main className="realPanelState"><h1>Inicia sesión</h1><a className="primaryBtn" href="/">Ingresar</a></main>;if(!t)return <main className="realPanelState"><h1>No tienes acceso a este torneo</h1><a href="/panel">Volver</a></main>;const registeredApplicationIds=new Set(teams.map(x=>x.application_id).filter(Boolean));
 return <main className="tAdmin"><header><a href="/panel">← Mis torneos</a><div><span className="sectionLabel">ADMINISTRACIÓN</span><h1>{t.name}</h1></div><button className="primaryBtn" onClick={copy}>Copiar enlace de inscripción</button></header>{message&&<div className="adminMessage">{message}<button onClick={()=>setMessage("")}>×</button></div>}<nav>{[["equipos","Equipos"],["canchas","Canchas"],["calendario","Calendario"],["config","Configuración"]].map(([k,l])=><button className={tab===k?"active":""} onClick={()=>setTab(k)} key={k}>{l}</button>)}</nav>
 {tab==="equipos"&&<section><div className="adminGrid"><div><h2>Solicitudes</h2>{apps.length?apps.map(a=><article className="adminRow" key={a.id}><div><b>{a.team_name}</b><small>{a.representative_name} · {a.requested_role==="coach"?"Técnico":"Propietario"}</small></div><span>{a.status==="approved"?registeredApplicationIds.has(a.id)?"Equipo creado":"Aprobada · falta crear equipo":a.status}</span>{a.status==="pending"&&<div><button onClick={()=>review(a,"approved")}>Aprobar</button><button onClick={()=>review(a,"rejected")}>Rechazar</button></div>}{a.status==="approved"&&!registeredApplicationIds.has(a.id)&&<button onClick={()=>completeApprovedTeam(a)}>Crear ficha del equipo</button>}</article>):<p>No hay solicitudes pendientes.</p>}</div><form className="adminForm" onSubmit={addTeam}><h2>Registrar equipo directamente</h2><label>Nombre<input name="name" required/></label><label>Técnico<input name="coach"/></label><div className="formPair"><label>Camisa<input name="shirt" placeholder="Azul"/></label><label>Pantaloneta<input name="shorts" placeholder="Blanca"/></label></div><label>Medias<input name="socks" placeholder="Azules"/></label><button className="primaryBtn">Registrar y aprobar</button></form></div><h2>Equipos inscritos ({teams.length})</h2>{teams.map(x=><article className="adminRow" key={x.id}><div><b>{x.name}</b><small>{x.coach_name||"Sin técnico"} · Camisa {x.shirt_color||"sin definir"}</small></div><span>{x.approved?"Aprobado":"Pendiente"}</span><a className="teamEditButton" href={`/equipos/${x.id}/administrar`}>Ver y editar →</a></article>)}</section>}
 {tab==="canchas"&&<section><div className="adminGrid"><form className="adminForm" onSubmit={addVenue}><h2>Nueva cancha</h2><label>Nombre<input name="name" required/></label><label>Dirección<input name="address"/></label><button className="primaryBtn">Agregar cancha</button></form><div><h2>Canchas registradas</h2>{venues.map(v=><article className="adminRow" key={v.id}><div><b>{v.name}</b><small>{v.address||"Sin dirección"}</small><small>ID: {v.id}</small></div></article>)}</div></div></section>}
 {tab==="calendario"&&<section><div className="calendarActions"><button className="primaryBtn" onClick={autoSchedule}>Generar calendario automático</button><span>Usará {t.round_robin_legs||1} vuelta(s), la fecha inicial y las canchas registradas.</span></div><form className="adminForm horizontal" onSubmit={addMatch}><select name="home" required><option value="">Local</option>{teams.filter(x=>x.approved).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><select name="away" required><option value="">Visitante</option>{teams.filter(x=>x.approved).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><input type="datetime-local" name="date" required/><select name="venue"><option value="">Sin cancha</option>{venues.map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select><button className="primaryBtn">Agregar partido</button></form>{matches.map(m=><article className="adminRow" key={m.id}><div><b>{m.home?.name} vs {m.away?.name}</b><small>{m.scheduled_at?new Date(m.scheduled_at).toLocaleString("es-CO"):"Por definir"} · {m.venue?.name||"Sin cancha"}</small></div><span>Fecha {m.round_number||"manual"}</span><button onClick={()=>updateMatch(m)}>Editar</button></article>)}</section>}
 {tab==="config"&&<section><form className="adminForm settings" onSubmit={saveSettings}><h2>Editar torneo</h2><label>Nombre<input name="name" defaultValue={t.name} required/></label><div className="formPair"><label>Inicio<input type="date" name="startDate" defaultValue={t.start_date}/></label><label>Estado<select name="status" defaultValue={t.status}><option value="registration">Inscripciones</option><option value="in_progress">En curso</option><option value="finished">Finalizado</option></select></label></div><div className="formPair"><label>Formato del torneo<select name="format" defaultValue={t.format||"round_robin_knockout"}><option value="round_robin_knockout">Todos contra todos</option><option value="groups_knockout">Fase de grupos</option></select></label><label>Fase después de clasificar<select name="nextStage" defaultValue={t.next_stage_format||"knockout"}><option value="knockout">Eliminación directa</option><option value="round_robin">Otro todos contra todos</option></select></label></div><div className="formPair"><label>Jugadores en cancha<input type="number" min="5" max="11" name="players" defaultValue={t.players_on_field}/></label><label>Clasificados<input type="number" min="1" name="qualifiers" defaultValue={t.qualifiers}/></label></div><div className="formPair"><label>Vueltas de todos contra todos<select name="legs" defaultValue={t.round_robin_legs||1}><option value="1">Una vuelta</option><option value="2">Dos vueltas</option></select></label><label>Valor por equipo<input type="number" min="0" name="fee" defaultValue={t.registration_fee}/></label></div><button className="primaryBtn">Guardar cambios</button></form></section>}</main>;
}
