"use client";
/* eslint-disable @next/next/no-img-element, @typescript-eslint/no-explicit-any, react-hooks/exhaustive-deps */
import { FormEvent,useEffect,useMemo,useState } from "react";
import { getSupabaseBrowserClient } from "../lib/supabase/client";
import "./platform.css";import "./platform-overrides.css";
export function TournamentAdvertisingAdmin({id}:{id:string}){
 const supabase=useMemo(()=>getSupabaseBrowserClient(),[]),[t,setT]=useState<any>(null),[ads,setAds]=useState<any[]>([]),[user,setUser]=useState<any>(null),[loading,setLoading]=useState(true),[uploading,setUploading]=useState(false),[message,setMessage]=useState("");
 const load=async()=>{if(!supabase)return;const {data:{user:u}}=await supabase.auth.getUser();setUser(u);if(!u)return setLoading(false);const {data:tournament}=await supabase.from("tournaments").select("id,name,slug,owner_id,organizations(slug)").eq("id",id).eq("owner_id",u.id).maybeSingle();setT(tournament);if(tournament){const {data}=await supabase.from("tournament_ads").select("*").eq("tournament_id",id).order("display_order").order("created_at");setAds(data??[]);}setLoading(false);};
 useEffect(()=>{void load();},[supabase,id]);
 const add=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form),file=f.get("image") as File|null;if(!file?.size)return setMessage("Selecciona una imagen para el banner.");if(!["image/jpeg","image/png","image/webp"].includes(file.type))return setMessage("Usa una imagen JPG, PNG o WebP.");if(file.size>8*1024*1024)return setMessage("La imagen no puede superar 8 MB.");setUploading(true);const ext=file.name.split(".").pop()?.toLowerCase()||"jpg",path=`${id}/${crypto.randomUUID()}.${ext}`,uploaded=await supabase!.storage.from("tournament-ads").upload(path,file,{contentType:file.type,upsert:false});if(uploaded.error){setUploading(false);return setMessage(uploaded.error.message);}const {data:url}=supabase!.storage.from("tournament-ads").getPublicUrl(path),rawLink=String(f.get("link")||"").trim(),link=rawLink&&!/^https?:\/\//i.test(rawLink)?`https://${rawLink}`:rawLink;const {error}=await supabase!.from("tournament_ads").insert({tournament_id:id,title:String(f.get("title")||"").trim()||null,image_url:url.publicUrl,storage_path:path,link_url:link||null,display_order:Number(f.get("order")||0),active:true,created_by:user.id});if(error){await supabase!.storage.from("tournament-ads").remove([path]);setMessage(error.message);}else{form.reset();setMessage("Publicidad agregada al banner.");await load();}setUploading(false);};
 const toggle=async(ad:any)=>{const {error}=await supabase!.from("tournament_ads").update({active:!ad.active,updated_at:new Date().toISOString()}).eq("id",ad.id);setMessage(error?error.message:ad.active?"Publicidad pausada.":"Publicidad activada.");if(!error)await load();};
 const remove=async(ad:any)=>{if(!confirm("¿Eliminar esta publicidad del torneo?"))return;const {error}=await supabase!.from("tournament_ads").delete().eq("id",ad.id);if(error)return setMessage(error.message);await supabase!.storage.from("tournament-ads").remove([ad.storage_path]);setMessage("Publicidad eliminada.");await load();};
 if(loading)return <main className="realPanelState"><h1>Cargando publicidad…</h1></main>;if(!user)return <main className="realPanelState"><h1>Inicia sesión</h1><a className="primaryBtn" href="/">Ingresar</a></main>;if(!t)return <main className="realPanelState"><h1>No tienes acceso a este torneo</h1><a href="/panel">Volver</a></main>;
 const org=Array.isArray(t.organizations)?t.organizations[0]:t.organizations;
 return <main className="tAdmin advertisingPage"><header><a href={`/panel/torneos/${id}`}>← Volver al torneo</a><div><span className="sectionLabel">ADMINISTRACIÓN</span><h1>{t.name}</h1></div><a className="outlineBtn" href={`/organizaciones/${org.slug}/torneos/${t.slug}`} target="_blank">Ver página pública ↗</a></header>{message&&<div className="adminMessage">{message}<button onClick={()=>setMessage("")}>×</button></div>}<section className="advertisingAdmin"><div className="advertisingIntro"><div><p className="sectionLabel">BANNER PÚBLICO</p><h2>Publicidad del torneo</h2><p>Las imágenes activas rotarán automáticamente sin ocultar la información ni los botones del torneo.</p></div></div><div className="advertisingLayout"><form className="adminForm" onSubmit={add}><h3>Nueva publicidad</h3><label>Imagen del banner<input name="image" type="file" accept="image/jpeg,image/png,image/webp" required/><small>Recomendado: 1600 × 600 px · máximo 8 MB</small></label><label>Nombre o referencia<input name="title" placeholder="Patrocinador principal"/></label><label>Enlace opcional<input name="link" placeholder="https://patrocinador.com"/></label><label>Orden de aparición<input name="order" type="number" min="0" defaultValue={ads.length}/></label><button className="primaryBtn" disabled={uploading}>{uploading?"Cargando…":"Agregar al banner"}</button></form><div className="advertisingList">{ads.length?ads.map(ad=><article className={!ad.active?"pausedAd":""} key={ad.id}><img src={ad.image_url} alt={ad.title||"Publicidad"}/><div><b>{ad.title||"Publicidad sin nombre"}</b><small>Orden {ad.display_order} · {ad.active?"Visible":"Pausada"}</small></div><button onClick={()=>toggle(ad)}>{ad.active?"Pausar":"Activar"}</button><button className="dangerButton" onClick={()=>remove(ad)}>Eliminar</button></article>):<div className="emptyAdvertising"><span>🖼️</span><h3>Aún no hay publicidad</h3><p>Mientras tanto, el banner seguirá mostrando el logo del torneo.</p></div>}</div></div></section></main>;
}
