"use client";
/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-img-element, @typescript-eslint/no-explicit-any, react-hooks/exhaustive-deps */
import { FormEvent,useEffect,useMemo,useState } from "react";
import { getSupabaseBrowserClient } from "../lib/supabase/client";
import { PublicBracket } from "./public-bracket";
import "./platform.css";import "./platform-overrides.css";
const slugify=(v:string)=>v.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
const sections=[["equipos","Equipos"],["partidos","Partidos"],["posiciones","Posiciones"],["goleadores","Goleadores"],["valla","Valla"],["eliminacion","Eliminación"]] as const;
type Section=(typeof sections)[number][0];
export function TournamentPortal({slug}:{slug:string}){
 const supabase=useMemo(()=>getSupabaseBrowserClient(),[]),[tournament,setTournament]=useState<any>(null),[teams,setTeams]=useState<any[]>([]),[matches,setMatches]=useState<any[]>([]),[standings,setStandings]=useState<any[]>([]),[scorers,setScorers]=useState<any[]>([]),[goalkeepers,setGoalkeepers]=useState<any[]>([]),[ads,setAds]=useState<any[]>([]),[adIndex,setAdIndex]=useState(0),[activeSection,setActiveSection]=useState<Section>("partidos"),[user,setUser]=useState<any>(null),[application,setApplication]=useState<any>(null),[myTeam,setMyTeam]=useState<any>(null),[showJoin,setShowJoin]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 const load=async()=>{if(!supabase)return;const {data:{user:u}}=await supabase.auth.getUser();setUser(u);const {data:t}=await supabase.from("tournaments").select("*,organizations(slug,name)").eq("slug",slug).eq("is_public",true).maybeSingle();setTournament(t);if(t){const [a,b,c,d,e,f]=await Promise.all([supabase.from("teams").select("id,name,crest_url").eq("tournament_id",t.id).eq("approved",true),supabase.from("matches").select("id,scheduled_at,status,home_score,away_score,home:teams!matches_home_team_id_fkey(name,crest_url),away:teams!matches_away_team_id_fkey(name,crest_url),phase:phases(id,name,phase_type,sequence,status)").eq("tournament_id",t.id).order("scheduled_at"),supabase.from("team_standings").select("*").eq("tournament_id",t.id).is("phase_id",null).order("points",{ascending:false}).order("goal_difference",{ascending:false}),supabase.from("match_events").select("player_id,event_type,player:players!match_events_player_id_fkey(id,full_name,jersey_number,photo_url,team:teams!players_team_id_fkey(id,name,crest_url)),match:matches!inner(tournament_id)").eq("match.tournament_id",t.id).in("event_type",["goal","penalty_scored"]).not("player_id","is",null),supabase.from("players").select("id,full_name,jersey_number,position,photo_url,team:teams!players_team_id_fkey!inner(id,name,crest_url,tournament_id)").eq("team.tournament_id",t.id).eq("active",true).or("position.ilike.%arquero%,position.ilike.%portero%"),supabase.from("tournament_ads").select("id,title,image_url,link_url,display_order").eq("tournament_id",t.id).eq("active",true).order("display_order").order("created_at")]);setTeams(a.data??[]);setMatches(b.data??[]);setStandings(c.data??[]);setAds(f.data??[]);
 const scorerMap=new Map<string,any>();for(const event of d.data??[]){const player=event.player as any;if(!player?.id)continue;const current=scorerMap.get(player.id);if(current)current.goals+=1;else scorerMap.set(player.id,{...player,goals:1});}const ranked=await Promise.all(Array.from(scorerMap.values()).map(async scorer=>{if(!scorer.photo_url)return{...scorer,photo_preview:null};if(/^https?:\/\//i.test(scorer.photo_url))return{...scorer,photo_preview:scorer.photo_url};const {data:signed}=await supabase.storage.from("player-photos").createSignedUrl(scorer.photo_url,3600);return{...scorer,photo_preview:signed?.signedUrl||null};}));setScorers(ranked.sort((x,y)=>y.goals-x.goals||x.full_name.localeCompare(y.full_name,"es")));
 const keeperByTeam=new Map<string,any>();for(const keeper of e.data??[]){const team=(keeper as any).team;if(team?.id&&!keeperByTeam.has(team.id))keeperByTeam.set(team.id,keeper);}const keeperPreviews=await Promise.all(Array.from(keeperByTeam.entries()).map(async([teamId,keeper])=>{if(!keeper.photo_url)return[teamId,{...keeper,photo_preview:null}] as const;if(/^https?:\/\//i.test(keeper.photo_url))return[teamId,{...keeper,photo_preview:keeper.photo_url}] as const;const {data:signed}=await supabase.storage.from("player-photos").createSignedUrl(keeper.photo_url,3600);return[teamId,{...keeper,photo_preview:signed?.signedUrl||null}] as const;}));const keepersWithPhotos=new Map(keeperPreviews);setGoalkeepers((c.data??[]).filter(row=>Number(row.played||0)>0).map(row=>({...row,team_id:row.team_id||"",team_name:row.team_name||"Equipo",played:Number(row.played||0),goals_against:Number(row.goals_against||0),goalkeeper:keepersWithPhotos.get(row.team_id||"")||null})).sort((x,y)=>x.goals_against-y.goals_against||y.played-x.played||x.team_name.localeCompare(y.team_name,"es")));
 if(u){const [ap,mt]=await Promise.all([supabase.from("team_applications").select("*").eq("tournament_id",t.id).eq("applicant_id",u.id).order("created_at",{ascending:false}).limit(1).maybeSingle(),supabase.from("teams").select("*").eq("tournament_id",t.id).eq("owner_id",u.id).maybeSingle()]);setApplication(ap.data);setMyTeam(mt.data);}}setLoading(false);};
 useEffect(()=>{void load();},[supabase,slug]);
 useEffect(()=>{if(!loading&&new URLSearchParams(location.search).get("inscribir")==="1")setShowJoin(true);const hash=location.hash.slice(1) as Section;if(sections.some(([key])=>key===hash))setActiveSection(hash);},[loading]);
 useEffect(()=>{if(ads.length<2)return;const timer=window.setInterval(()=>setAdIndex(i=>(i+1)%ads.length),5500);return()=>window.clearInterval(timer);},[ads.length]);
 const login=()=>supabase?.auth.signInWithOAuth({provider:"google",options:{redirectTo:location.href}});
 const apply=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!user)return void login();const f=new FormData(e.currentTarget);const {error}=await supabase!.from("team_applications").insert({tournament_id:tournament.id,applicant_id:user.id,team_name:String(f.get("team")),representative_name:String(f.get("representative")),requested_role:String(f.get("role")),phone:String(f.get("phone")),email:user.email||null,city:String(f.get("city")||""),message:String(f.get("message")||"")});setMessage(error?error.message:"Solicitud enviada. El organizador debe aprobarla.");if(!error){setShowJoin(false);await load();}};
 const registerTeam=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),name=String(f.get("name"));const {data,error}=await supabase!.from("teams").insert({tournament_id:tournament.id,owner_id:user.id,application_id:application.id,name,slug:`${slugify(name)}-${Date.now().toString().slice(-5)}`,coach_name:String(f.get("coach")||""),shirt_color:String(f.get("shirt")),shorts_color:String(f.get("shorts")),socks_color:String(f.get("socks")),approved:true,approved_by:tournament.owner_id,approved_at:new Date().toISOString()}).select().single();setMessage(error?error.message:"Equipo registrado. Ahora completa los jugadores.");if(data)location.href=`/equipos/${data.id}/administrar`;};
 const selectSection=(section:Section)=>{setActiveSection(section);history.replaceState(null,"",`${location.pathname}${location.search}#${section}`);document.querySelector(".portalTabs")?.scrollIntoView({behavior:"smooth",block:"start"});};
 const orderedMatches=useMemo(()=>{const now=Date.now();return [...matches].sort((a,b)=>{const at=a.scheduled_at?new Date(a.scheduled_at).getTime():Number.MAX_SAFE_INTEGER,bt=b.scheduled_at?new Date(b.scheduled_at).getTime():Number.MAX_SAFE_INTEGER,aGroup=a.status==="in_progress"?0:["scheduled","lineup_open"].includes(a.status)?1:2,bGroup=b.status==="in_progress"?0:["scheduled","lineup_open"].includes(b.status)?1:2;if(aGroup!==bGroup)return aGroup-bGroup;if(aGroup<2)return Math.abs(at-now)-Math.abs(bt-now);return bt-at;});},[matches]);
 if(loading)return <main className="portalState"><p>Cargando campeonato…</p></main>;if(!tournament)return <main className="portalState"><h1>Este torneo no existe</h1><a href="/">Volver</a></main>;
 const joinLabel=myTeam?"Administrar mi equipo":application?.status==="approved"?"Registrar mi equipo":application?.status==="pending"?"Solicitud pendiente":"Inscribir mi equipo",isOwner=user?.id===tournament.owner_id,primaryLabel=isOwner?"Administrar torneo":joinLabel;
 const openPrimary=()=>{if(isOwner)location.href=`/panel/torneos/${tournament.id}`;else if(myTeam)location.href=`/equipos/${myTeam.id}/administrar`;else setShowJoin(true);};
 const knockoutMatches=matches.filter(match=>match.phase?.phase_type==="knockout"),crestFor=(teamId:string)=>teams.find(team=>team.id===teamId)?.crest_url||"/liguita-logo-google-white.png",currentAd=ads[adIndex],heroImage=currentAd?.image_url||tournament.image_url||"/liguita-logo-white.png",matchStatus=(status:string)=>status==="scheduled"?"Programado":status==="lineup_open"?"Planilla abierta":status==="in_progress"?"En curso":status==="finished"?"Finalizado":status==="postponed"?"Aplazado":"Cancelado";
 return <main className="publicPortal"><header><a href="/"><img src="/liguita-logo-google-white.png" alt="Liguita"/>LIGUITA</a><button onClick={openPrimary}>{primaryLabel}</button></header>
 <section className="portalHero dynamicHero" style={{backgroundImage:`linear-gradient(90deg,#042f27ed,#073f3288),url(${heroImage})`}}><div className="heroTournamentContent"><span>{tournament.status.replace("_"," ")}</span><h1>{tournament.name}</h1><p>{tournament.description||"Toda la información oficial del campeonato."}</p><div>📅 Inicia {new Date(`${tournament.start_date}T12:00:00`).toLocaleDateString("es-CO")} · ⚽ {tournament.players_on_field} jugadores · 🏆 {tournament.qualifiers} clasifican</div><button className="primaryBtn" onClick={openPrimary}>{primaryLabel} →</button>{currentAd?.link_url&&<a className="heroAdLink" href={currentAd.link_url} target="_blank" rel="noreferrer">Visitar anunciante ↗</a>}{message&&<p>{message}</p>}</div>{ads.length>1&&<><button className="carouselArrow previous" aria-label="Publicidad anterior" onClick={()=>setAdIndex(i=>(i-1+ads.length)%ads.length)}>‹</button><button className="carouselArrow next" aria-label="Publicidad siguiente" onClick={()=>setAdIndex(i=>(i+1)%ads.length)}>›</button><div className="carouselDots">{ads.map((ad,index)=><button key={ad.id} aria-label={`Ver publicidad ${index+1}`} className={index===adIndex?"active":""} onClick={()=>setAdIndex(index)}/>)}</div></>}</section>
 <nav className="portalTabs" aria-label="Secciones del torneo">{sections.filter(([key])=>key!=="eliminacion"||knockoutMatches.length>0).map(([key,label])=><button key={key} className={activeSection===key?"active":""} onClick={()=>selectSection(key)}>{label}</button>)}</nav>
 {activeSection==="equipos"&&<section id="equipos" className="portalSection portalActiveSection"><p className="sectionLabel">PARTICIPANTES</p><h2>Equipos inscritos</h2><div className="teamTiles">{teams.length?teams.map(x=><article key={x.id}><img src={x.crest_url||"/liguita-logo-google-white.png"} alt=""/><b>{x.name}</b></article>):<p>Aún no hay equipos aprobados.</p>}</div></section>}
 {activeSection==="partidos"&&<section id="partidos" className="portalSection soft portalActiveSection"><p className="sectionLabel">CALENDARIO</p><h2>Partidos programados</h2>{orderedMatches.length?orderedMatches.map((m,index)=><article className={`publicMatch ${index===0?"featuredMatch":""}`} key={m.id}>{index===0&&<b className="nearestMatchLabel">{m.status==="in_progress"?"EN JUEGO":m.scheduled_at&&new Date(m.scheduled_at).toDateString()===new Date().toDateString()?"PARTIDO DE HOY":"PARTIDO MÁS PRÓXIMO"}</b>}<span>{m.scheduled_at?new Date(m.scheduled_at).toLocaleString("es-CO"):"Por programar"}</span><b className="publicMatchTeams"><span><img src={m.home?.crest_url||"/liguita-logo-google-white.png"} alt=""/>{m.home?.name}</span><strong>{m.home_score} — {m.away_score}</strong><span><img src={m.away?.crest_url||"/liguita-logo-google-white.png"} alt=""/>{m.away?.name}</span></b><small className={`publicMatchStatus ${m.status}`}>{matchStatus(m.status)}</small></article>):<p>Los partidos aparecerán cuando el organizador publique el calendario.</p>}</section>}
 {activeSection==="posiciones"&&<section id="posiciones" className="portalSection portalActiveSection"><p className="sectionLabel">CLASIFICACIÓN</p><h2>Tabla de posiciones</h2><div className="portalTable"><table><thead><tr><th>#</th><th>Equipo</th><th>PJ</th><th>PG</th><th>PE</th><th>PP</th><th>GF</th><th>GC</th><th>DG</th><th>PTS</th></tr></thead><tbody>{standings.map((s,i)=><tr className={i<Number(tournament.qualifiers||0)?"qualifiedRow":"eliminatedRow"} key={s.team_id}><td>{i+1}</td><td><span className="standingTeam"><img src={crestFor(s.team_id)} alt=""/>{s.team_name}</span></td><td>{s.played}</td><td>{s.wins}</td><td>{s.draws}</td><td>{s.losses}</td><td>{s.goals_for}</td><td>{s.goals_against}</td><td className={s.goal_difference>0?"positiveGoalDiff":s.goal_difference<0?"negativeGoalDiff":""}>{s.goal_difference>0?`+${s.goal_difference}`:s.goal_difference}</td><td><b>{s.points}</b></td></tr>)}</tbody></table></div><div className="standingsLegend"><span><i className="qualifiedSwatch"/>Zona de clasificación</span><span><i className="eliminatedSwatch"/>Zona de eliminación</span></div></section>}
 {activeSection==="eliminacion"&&knockoutMatches.length>0&&<PublicBracket matches={knockoutMatches} qualifiers={Number(tournament.qualifiers||2)}/>}
 {activeSection==="goleadores"&&<section id="goleadores" className="portalSection soft scorersSection portalActiveSection"><p className="sectionLabel">ARTILLEROS</p><h2>Tabla de goleadores</h2>{scorers.length?<div className="publicScorers">{scorers.map((scorer,index)=><article key={scorer.id}><b className="scorerRank">{index+1}</b><div className="scorerPhoto">{scorer.photo_preview?<img src={scorer.photo_preview} alt={scorer.full_name}/>:<span>{scorer.full_name.slice(0,1).toUpperCase()}</span>}</div><div className="scorerIdentity"><small>#{scorer.jersey_number||"—"}</small><h3>{scorer.full_name}</h3><p><img src={scorer.team?.crest_url||"/liguita-logo-google-white.png"} alt=""/>{scorer.team?.name||"Equipo por definir"}</p></div><div className="scorerGoals"><strong>{scorer.goals}</strong><span>{scorer.goals===1?"GOL":"GOLES"}</span></div></article>)}</div>:<div className="emptyScorers"><span>⚽</span><h3>Aún no hay goleadores</h3><p>La tabla aparecerá al registrar el primer gol del torneo.</p></div>}</section>}
 {activeSection==="valla"&&<section id="valla" className="portalSection goalkeeperSection portalActiveSection"><p className="sectionLabel">SEGURIDAD BAJO LOS TRES PALOS</p><h2>Valla menos vencida</h2>{goalkeepers.length?<div className="publicScorers goalkeeperRanking">{goalkeepers.map((entry,index)=><article key={entry.team_id}><b className="scorerRank">{index+1}</b><div className="scorerPhoto keeperPhoto">{entry.goalkeeper?.photo_preview?<img src={entry.goalkeeper.photo_preview} alt={entry.goalkeeper.full_name}/>:<span>{entry.goalkeeper?.full_name?.slice(0,1).toUpperCase()||"🧤"}</span>}</div><div className="scorerIdentity"><small>{entry.goalkeeper?"#"+(entry.goalkeeper.jersey_number||"—")+" · ARQUERO":"ARQUERO POR DEFINIR"}</small><h3>{entry.goalkeeper?.full_name||entry.team_name}</h3><p><img src={entry.crest_url||crestFor(entry.team_id)} alt=""/>{entry.team_name} · {entry.played} PJ</p></div><div className="scorerGoals keeperGoals"><strong>{entry.goals_against}</strong><span>{entry.goals_against===1?"GOL RECIBIDO":"GOLES RECIBIDOS"}</span></div></article>)}</div>:<div className="emptyScorers"><span>🧤</span><h3>Aún no hay clasificación</h3><p>Aparecerá cuando finalice el primer partido del torneo.</p></div>}</section>}
 {showJoin&&<div className="createOverlay">{!user?<div className="authCard"><button className="modalClose" onClick={()=>setShowJoin(false)}>×</button><h2>Ingresa para inscribir tu equipo</h2><p>Usaremos tu cuenta para que después puedas administrar jugadores y uniforme.</p><button className="googleAuthBtn" onClick={login}>Continuar con Google</button></div>:application?.status==="approved"&&!myTeam?<form className="createTournament" onSubmit={registerTeam}><button type="button" className="modalClose" onClick={()=>setShowJoin(false)}>×</button><h2>Registra tu equipo</h2><label>Nombre<input name="name" defaultValue={application.team_name} required/></label><label>Técnico<input name="coach" defaultValue={application.requested_role==="coach"?application.representative_name:""}/></label><div className="formPair"><label>Camisa<input name="shirt" required placeholder="Azul"/></label><label>Pantaloneta<input name="shorts" required placeholder="Blanca"/></label></div><label>Medias<input name="socks" required placeholder="Azules"/></label><button className="primaryBtn">Guardar equipo</button></form>:application?<div className="authCard"><button className="modalClose" onClick={()=>setShowJoin(false)}>×</button><h2>Solicitud {application.status}</h2><p>{application.status==="pending"?"El organizador todavía debe revisarla.":"Puedes comunicarte con el organizador o enviar una nueva solicitud."}</p></div>:<form className="createTournament" onSubmit={apply}><button type="button" className="modalClose" onClick={()=>setShowJoin(false)}>×</button><p className="sectionLabel">INSCRIPCIÓN</p><h2>Solicitar cupo</h2><label>Quiero registrarme como<select name="role"><option value="owner">Propietario del equipo</option><option value="coach">Técnico</option></select></label><label>Nombre del equipo<input name="team" required/></label><label>Tu nombre<input name="representative" required defaultValue={user.user_metadata?.full_name||""}/></label><div className="formPair"><label>Celular<input name="phone" required/></label><label>Ciudad<input name="city"/></label></div><label>Mensaje<textarea name="message" rows={2}/></label><button className="primaryBtn">Enviar solicitud</button></form>}</div>}
 </main>;
}
