import { integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const users = sqliteTable("users", { id: text().primaryKey(), email: text().notNull(), name: text().notNull(), role: text().notNull(), createdAt: integer("created_at").notNull() }, t => [uniqueIndex("idx_users_email").on(t.email)]);
export const tournaments = sqliteTable("tournaments", { id: text().primaryKey(), ownerId: text("owner_id").notNull(), name: text().notNull(), slug: text().notNull(), format: text().notNull(), teamsLimit: integer("teams_limit").notNull(), qualifiers: integer().notNull(), nextPhase: text("next_phase").notNull(), status: text().notNull() }, t => [uniqueIndex("idx_tournaments_slug").on(t.slug)]);
export const teams = sqliteTable("teams", { id: text().primaryKey(), tournamentId: text("tournament_id").notNull(), coachId: text("coach_id"), name: text().notNull(), crestKey: text("crest_key"), status: text().notNull() });
export const players = sqliteTable("players", { id: text().primaryKey(), teamId: text("team_id").notNull(), name: text().notNull(), document: text().notNull(), number: integer(), position: text(), photoKey: text("photo_key"), approved: integer({ mode: "boolean" }).notNull() }, t => [uniqueIndex("idx_players_team_document").on(t.teamId, t.document)]);
export const matches = sqliteTable("matches", { id: text().primaryKey(), tournamentId: text("tournament_id").notNull(), phase: text().notNull(), round: integer().notNull(), homeId: text("home_id").notNull(), awayId: text("away_id").notNull(), startsAt: integer("starts_at").notNull(), venue: text(), scorerId: text("scorer_id"), status: text().notNull() });
export const matchEvents = sqliteTable("match_events", { id: text().primaryKey(), matchId: text("match_id").notNull(), playerId: text("player_id").notNull(), type: text().notNull(), minute: integer().notNull(), detail: text() });
export const ratings = sqliteTable("ratings", { id: text().primaryKey(), playerId: text("player_id").notNull(), userId: text("user_id").notNull(), value: real().notNull() }, t => [uniqueIndex("idx_ratings_player_user").on(t.playerId, t.userId)]);
export const banners = sqliteTable("banners", { id: text().primaryKey(), tournamentId: text("tournament_id").notNull(), imageKey: text("image_key").notNull(), link: text(), position: integer().notNull(), active: integer({ mode: "boolean" }).notNull() });
